.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH getquotes 1  "getquotes " 
.SH NAME
getquotes \- A simple cli tool to get quotes in your terminal using WikiQuotes
.SH SYNOPSIS
\fBgetquotes\fR [\fB\-a\fR|\fB\-\-authors\fR] [\fB\-t\fR|\fB\-\-theme\-color\fR] [\fB\-m\fR|\fB\-\-max\-tries\fR] [\fB\-l\fR|\fB\-\-log\-file\fR] [\fB\-r\fR|\fB\-\-rainbow\-mode\fR] [\fB\-i\fR|\fB\-\-init\-cache\fR] [\fB\-o\fR|\fB\-\-offline\fR] [\fB\-v\fR|\fB\-\-version\fR] [\fB\-C\fR|\fB\-\-config\fR] [\fB\-c\fR|\fB\-\-completion\fR] [\fB\-M\fR|\fB\-\-migrate\-config\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
A simple cli tool to get quotes in your terminal using WikiQuotes
.SH OPTIONS
.TP
\fB\-a\fR, \fB\-\-authors\fR=\fIAUTHORS\fR
Specify a list of authors to fetch quotes from
.TP
\fB\-t\fR, \fB\-\-theme\-color\fR=\fITHEME_COLOR\fR
Set the theme color for the displayed quotes
.TP
\fB\-m\fR, \fB\-\-max\-tries\fR=\fIMAX_TRIES\fR
Set the maximum number of tries to fetch a quote
.TP
\fB\-l\fR, \fB\-\-log\-file\fR=\fILOG_FILE\fR
Specify the log file path
.TP
\fB\-r\fR, \fB\-\-rainbow\-mode\fR
Enable rainbow mode for random quote colors
.TP
\fB\-i\fR, \fB\-\-init\-cache\fR
Initialize the quote cache for offline mode
.TP
\fB\-o\fR, \fB\-\-offline\fR
Run in offline mode, using cached quotes
.TP
\fB\-v\fR, \fB\-\-version\fR
Print version information
.TP
\fB\-C\fR, \fB\-\-config\fR=\fICONFIG\fR
Use a custom TOML configuration file
.TP
\fB\-c\fR, \fB\-\-completion\fR=\fICOMPLETION\fR
Generate shell completion script
.br

.br
[\fIpossible values: \fRbash, elvish, fish, powershell, zsh, nushell]
.TP
\fB\-M\fR, \fB\-\-migrate\-config\fR
Migrate JSON config to TOML format (will be removed in next major release)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH AUTHORS
MuntasirSZN <muntasir.joypurhat@gmail.com>
